- README.md
Fix the invalid link in README.md
Fixes: #2
> Fix invalid link

- concepts-and-principle/service-mesh-patterns.md
> Fix issue #15

- SUMMARY.md
- best-practices/how-to-implement-ingress-gateway.md
Signed-off-by: Huabing Zhao <zhao.huabing@zte.com.cn>
>  最佳实践：如何为服务网格选择入口网关

- appendix/service-mesh-landscape.md
> add Orange API Gateway

- SUMMARY.md
- concepts-and-principle/istio-cni.md
> add istio-cni.md

- intro/service-mesh-the-microservices-in-post-kubernetes-era.md
Fix some sentence mistakes.
/assgin @rootsongjc
> Fix some sentence mistakes

- concepts-and-principle/istio-sidecar-injector.md
Old url return a not found result.
> Fix sidecar-injection url

- SUMMARY.md
- control-plane/sidecar-injector.md
> istio-analysis-2:sidecar-injector

- OWNERS
- README.md
- In order to start the editing process, we create an editorial board with
initial 6 people https://github.com/servicemesher/istio-handbook/issues/42
- Add them to OWNERS file
> Add Editorial Board

- OWNERS
- README.md
编委会增加两个新成员：
- 高步双（阿里云）
- 叶王（百度）
> Add two new members to editorial board

- package.json
- wg/process.md
> 增加 Gitbook 配置用于 netlify 预览

- .mergify.yml
更新 mergify 配置，将 `@servicemesher/istio-handbook-wg-maintainers` 作为 reviewer， 参考 https://doc.mergify.io/examples.html#id17
提交 PR 后请先自查以下内容：
- PR 的标题格式为：在空白文档中新增内容 `add: 文档标题`，修改已有内容的文档 `update：文档标题`。
- 在该 PR 已指明解决的 issue 链接：无
- 已阅读并保证所提交 PR 符合[写作规范](https://www.servicemesher.com/istio-handbook/wg/specification.html)。
- 文章内容格式请参考 PR [add: practice/jwt-authorization #186](https://github.com/servicemesher/istio-handbook/pull/186/files)。
- 保留下文中的声明。
- 我认可本书的版权信息：本书著作权归属于 [ServiceMesher 社区](https://www.servicemesher.com)，我将保留对所修改内容的署名权。
- 我已阅读[参与贡献说明]([https://github.com/servicemesher/istio-handbook#%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE](https://github.com/servicemesher/istio-handbook#参与贡献))，并加入了 [istio-handbook-wg](https://github.com/orgs/servicemesher/teams/istio-handbook-wg) GitHub team。
> update: mergify config

- SUMMARY.md
- practice/setup-in-kubernetes.md
提交 PR 后请先自查以下内容：
- PR 的标题格式为：在空白文档中新增内容 `add: 文档标题`，修改已有内容的文档 `update：文档标题`。
- 在该 PR 已指明解决的 issue 链接：https://github.com/servicemesher/istio-handbook/pull/192
- 已阅读并保证所提交 PR 符合[写作规范](https://www.servicemesher.com/istio-handbook/wg/specification.html)。
- 文章内容格式请参考 PR [add: practice/jwt-authorization #186](https://github.com/servicemesher/istio-handbook/pull/186/files)。
- 保留下文中的声明。
- 我认可本书的版权信息：本书著作权归属于 [ServiceMesher 社区](https://www.servicemesher.com)，我将保留对所修改内容的署名权。
- 我已阅读[参与贡献说明]([https://github.com/servicemesher/istio-handbook#%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE](https://github.com/servicemesher/istio-handbook#参与贡献))，并加入了 [istio-handbook-wg](https://github.com/orgs/servicemesher/teams/istio-handbook-wg) GitHub team。
> delete:Kubernetes 部署

- .github/PULL_REQUEST_TEMPLATE.md
> update: pr template

- concepts/overview.md
> fix:  concept/overview

- practice/setup-istio.md
Fix a typo
在完成项的 [ ] 内填入 x，如：- [x]
> update：setup istio

- practice/route.md
> add: VirtualService

- concepts/sidecar-traffic-route.md
> fix type error

- practice/setup-istio.md
> fix table display error

- practice/upgrade.md
> fix typo error

- practice/traffic-control.md
> add missing blank around letters

- appendix/service-mesh-landscape.md
在服务网格全景图中增加对 Apache APISIX 的介绍
在完成项的 [ ] 内填入 x，如：- [x]
> add: 在服务网格全景图中增加对 Apache APISIX 的介绍

- wg/editorial-board.md
在完成项的 [ ] 内填入 x，如：- [x]
因个人原因不再适合担任编委会成员
> remove: gorda
